# 数据源配置
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            # 主库数据源,数据源名称只能是小写字母
            master:
                #可以不配置，阿里的数据库连接池会通过url自动搜寻
                #driverClassName: com.mysql.cj.jdbc.Driver
                url: jdbc:mysql://127.0.0.1:3306/db_xinsite_release?useUnicode=true&characterEncoding=utf-8&serverTimezone=CTT&zeroDateTimeBehavior=convertToNull&useSSL=false
                username: root
                password: root
            # 从库数据源
            viceone:
                # 从数据源开关/默认关闭
                enabled: true
                #driverClassName: com.mysql.cj.jdbc.Driver
                url: jdbc:mysql://127.0.0.1:3306/db_xinsite_demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=CTT&zeroDateTimeBehavior=convertToNull&useSSL=false
                username: root
                password: root
            # 从库数据源sqlserver
            sqlserver:
                enabled: true
                #driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
                url: jdbc:sqlserver://LAPTOP-ss3zxx;DatabaseName=db_xinsite_sqlserver
                username: sa
                password: sa
            # 从库数据源oracle
            oracle:
                enabled: false
                driverClassName: oracle.jdbc.driver.OracleDriver
                url: jdbc:oracle:thin:@localhost:1521:orcl
                username: orcl
                password: orcl
            # 初始连接数
            initialSize: 3
            # 最小连接池数量
            minIdle: 10
            # 最大连接池数量
            maxActive: 20
            # 配置获取连接等待超时的时间
            maxWait: 60000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            minEvictableIdleTimeMillis: 300000
            # 配置一个连接在池中最大生存的时间，单位是毫秒
            maxEvictableIdleTimeMillis: 900000
            # 配置检测连接是否有效
            validationQuery: select 1 from dual
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            webStatFilter:
                enabled: true
            statViewServlet:
                enabled: true
                # 设置白名单，不填则允许所有访问
                allow:
                url-pattern: /druid/*
                # 控制台管理用户名和密码
                login-username:
                login-password:
            filter:
                stat:
                    enabled: true
                    # 慢SQL记录
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true