# 项目相关配置
product:
  # 名称
  name: XinSite Demo
  # 版本
  version: V2.0.0
  # 项目名称
  productName: XinSite Java演示系统
  # 项目描述
  description: xinsite快速开发
  # 版权年份
  copyrightYear: 2020
  # 版权所有
  copyrightAll: ZangXiaXin

# 特殊配置参数
config:
  # 获取ip地址开关
  is_enabled: true
  # 是否记录操作日志
  is_write_log: true
  # 可上传默认文件
  upload_filetype: "*.jpg;*.gif;*.bmp;*.png;*.doc;*.docx;*.xls;*.xlsx;*.pdf;*.ppt;*.rar;*.zip;*.txt"
  # 当前系统，超级管理员角色，隐藏角色
  super_role: 1
  # 只有超级管理员能看到的栏目
  super_items: 0
  # 当前系统，参数配置的栏目Id
  itemid: 18
  # 列表字段部分为密码状态，上线不显示
  field_password: true
  # 主数据库源druid名称，默认master
  master_database: master

# 服务器环境配置
server:
    # 服务器HTTP端口号
    port: 8080
    servlet:
        # 应用的访问路径
        context-path: /demo
        session:
          # session超时时间30分钟
          timeout: 1800s
    tomcat:
      # tomcat的URI编码
      uri-encoding: UTF-8
      # tomcat最大线程数，默认为200
      max-threads: 800
      # Tomcat启动初始化的线程数，默认值25
      min-spare-threads: 30

# Spring配置
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存,模板页面实时更新
    cache: false
  messages:
    # 国际化资源文件路径
    basename: config/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  jmx:
    default-domain: com.demo
  profiles:
    active: druid
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  30MB
  quartz:
#    job-store-type: memory #jdbc:数据库方式
#    jdbc:
#      initialize-schema: never #不初始化表结构
    properties: #相关属性配置
      org:
        quartz:
          scheduler:
            # 线程调度器实例名
            instanceName: quartzScheduler
            instanceId: AUTO
            #默认主机名和时间戳生成实例ID,可以是任何字符串，但对于所有调度程序来说，必须是唯一的 对应qrtz_scheduler_state INSTANCE_NAME字段
#          jobStore:
#            class: org.quartz.impl.jdbcjobstore.JobStoreTX #持久化配置
#            #我们仅为数据库制作了特定于数据库的代理
#            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
#            tablePrefix: QRTZ_ #数据库表前缀
#            isClustered: false #打开群集功能
#            clusterCheckinInterval: 10000 #默认60秒
#            #在被认为“失火”之前，调度程序将“容忍”一个Triggers将其下一个启动时间通过的毫秒数
#            useProperties: false #以指示JDBCJobStore将JobDataMaps中的所有值都作为字符串
          threadPool: #连接池
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true


# MyBatis
mybatis:
  configuration:
    # 下划线转驼峰,这里配置后，configLocation中配置文件可以省去
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mappings/**/*.xml
  type-aliases-package: com.xinsite.mybatis.datasource
# mapperLocations: classpath*:mappings/*.xml
# configLocation:  classpath:mybatis/mybatis-config.xml

# Shiro配置
shiro:
  user:
    # 登录地址
    loginUrl: /login.html
    # 权限认证失败地址
    unauthorizedUrl: /error/403.html
    # 验证码开关
    captchaEnabled: true
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain:
    # 设置cookie的有效访问路径
    path: /demo
    # 设置HttpOnly属性
    httpOnly: true
    # 设置记住我Cookie的过期时间(天)
    rememberExpireDays: 30
  session:
    # Session超时时间（默认30分钟）
    timeout: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /imageKaptcha,/login.html,/logout,/anon/*
  # 匹配链接
  urlPatterns: /build/*,/flow/*,/*